var dungeons=[
"Test Dungeon",
"Beach Cave",
"Beach Cave Pit",
"Drenched Bluff",
"Mt. Bristle",
"Mt. Bristle Peak",
"Waterfall Cave",
"Apple Woods",
"Craggy Coast",
"Side Path",
"Mt. Horn",
"Rock Path",
"Foggy Forest",
"Forest Path",
"Steam Cave",
"Upper Steam Cave",
"Steam Cave Peak",
"Amp Plains",
"Far Amp Plains",
"Amp Clearing",
"Northern Desert",
"Quicksand Cave",
"Quicksand Pit",
"Underground Lake",
"Crystal Cave",
"Crystal Crossing",
"Crystal Lake",
"Chasm Cave",
"Dark Hill",
"Sealed Ruin",
"Deep Sealed Ruin",
"Sealed Ruin Pit",
"Dusk Forest",
"Deep Dusk Forest",
"Treeshroud Forest",
"Brine Cave",
"Lower Brine Cave",
"Brine Cave Pit",
"Hidden Land",
"Hidden Highland",
"Old Ruins",
"Temporal Tower",
"Temporal Spire",
"Temporal Pinnacle",
"Mystifying Forest",
"Mystifying Forest Clearing",
"Blizzard Island",
"Crevice Cave",
"Lower Crevice Cave",
"Crevice Cave Pit",
"Surrounded Sea",
"Miracle Sea",
"Deep Miracle Sea",
"Miracle Seabed",
"Ice Aegis Cave",
"Regice Chamber",
"Rock Aegis Cave",
"Regirock Chamber",
"Steel Aegis Cave",
"Registeel Chamber",
"Aegis Cave Pit",
"Regigigas Chamber",
"Mt. Travail",
"The Nightmare",
"Spacial Rift",
"Deep Spacial Rift",
"Spacial Rift Bottom",
"Dark Crater",
"Deep Dark Crater",
"Dark Crater Pit",
"Concealed Ruins",
"Deep Concealed Ruins",
"Marine Resort",
"Bottomless Sea",
"Bottomless Sea Depths",
"Shimmer Desert",
"Shimmer Desert Pit",
"Mt. Avalanche",
"Mt. Avalanche Peak",
"Giant Volcano",
"Giant Volcano Peak",
"World Abyss",
"World Abyss Pit",
"Sky Stairway",
"Sky Stairway Apex",
"Mystery Jungle",
"Deep Mystery Jungle",
"Serenity River",
"Landslide Cave",
"Lush Prairie",
"Tiny Meadow",
"Labyrinth Cave",
"Oran Forest",
"Lake Afar",
"Happy Outlook",
"Mt. Mistral",
"Shimmer Hill",
"Lost Wilderness",
"Midnight Forest",
"Zero Isle North",
"Zero Isle East",
"Zero Isle West",
"Zero Isle South"
]
