var items=[
"Nothing",
"Stick",
"Iron Thorn",
"Silver Spike",
"Gold Fang",
"Cacnea Spike",
"Corsola Twig",
"Gravelerock",
"Geo Pebble",
"Gold Thorn",
"Rare Fossil",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"Mobile Scarf",
"Heal Ribbon",
"Twist Band",
"Scope Lens",
"Patsy Band",
"No-Stick Cap",
"Pierce Band",
"Joy Ribbon",
"X-Ray Specs",
"Persim Band",
"Power Band",
"Pecha Scarf",
"Insomniscope",
"Warp Scarf",
"Tight Belt",
"Sneak Scarf",
"Gold Ribbon",
"Goggle Specs",
"Diet Ribbon",
"Trap Scarf",
"Racket Band",
"Def. Scarf",
"Stamina Band",
"Plain Ribbon",
"Special Band",
"Zinc Band",
"Detect Band",
"$$$",
"Dodge Scarf",
"Bounce Band",
"Curve Band",
"Whiff Specs",
"No-Aim Scope",
"Lockon Specs",
"Munch Belt",
"Pass Scarf",
"Weather Band",
"Friend Bow",
"Beauty Scarf",
"Sun Ribbon",
"Lunar Ribbon",
"Golden Mask",
"Amber Tear",
"Icy Flute",
"Fiery Drum",
"Terra Cymbal",
"Aqua-Monica",
"Rock Horn",
"Grass Cornet",
"Sky Melodica",
"Miracle Chest",
"Wonder Chest",
"$$$",
"Heal Seed",
"Oran Berry",
"Sitrus Berry",
"Eyedrop Seed",
"Reviver Seed",
"Blinker Seed",
"Doom Seed",
"X-Eye Seed",
"Life Seed",
"Rawst Berry",
"Hunger Seed",
"Quick Seed",
"Pecha Berry",
"Cheri Berry",
"Totter Seed",
"Sleep Seed",
"Plain Seed",
"Warp Seed",
"Blast Seed",
"Ginseng",
"Joy Seed",
"Chesto Berry",
"Stun Seed",
"Gabite Scale",
"Golden Seed",
"Vile Seed",
"Pure Seed",
"Violent Seed",
"Vanish Seed",
"$$$",
"Max Elixir",
"Protein",
"Calcium",
"Iron",
"Nectar",
"$$$",
"$$$",
"$$$",
"$$$",
"Zinc",
"Apple",
"Big Apple",
"Grimy Food",
"Huge Apple",
"$$$",
"$$$",
"Golden Apple",
"$$$",
"$$$",
"$$$",
"White Gummi",
"Red Gummi",
"Blue Gummi",
"Grass Gummi",
"Yellow Gummi",
"Clear Gummi",
"Orange Gummi",
"Pink Gummi",
"Brown Gummi",
"Sky Gummi",
"Gold Gummi",
"Green Gummi",
"Gray Gummi",
"Purple Gummi",
"Royal Gummi",
"Black Gummi",
"Silver Gummi",
"Wonder Gummi",
"$$$",
"$$$",
"Upgrade",
"King~27s Rock",
"Thunderstone",
"Deepseascale",
"Deepseatooth",
"Sun Stone",
"Moon Stone",
"Fire Stone",
"Water Stone",
"Metal Coat",
"Leaf Stone",
"Dragon Scale",
"Link Cable",
"Dubious Disc",
"Protector",
"Reaper Cloth",
"Razor Fang",
"Razor Claw",
"Electirizer",
"Magmarizer",
"Oval Stone",
"Dawn Stone",
"Shiny Stone",
"Dusk Stone",
"Coronet Rock",
"Mossy Rock",
"Frozen Rock",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"Mystery Part",
"Secret Slab",
"$$$",
"$$$",
"$$$",
"Wonder Egg",
"$$$",
"$$$",
"$$$",
"Key",
"Pok\351",
"$$$",
"$$$",
"Lost Loot",
"[M:I0]Used TM",
"[M:I0]Focus Punch",
"[M:I0]Dragon Claw",
"[M:I0]Water Pulse",
"[M:I0]Calm Mind",
"[M:I0]Roar",
"[M:I0]Toxic",
"[M:I0]Hail",
"[M:I0]Bulk Up",
"[M:I0]Bullet Seed",
"[M:I0]Hidden Power",
"$$$",
"[M:I0]Taunt",
"[M:I0]Ice Beam",
"[M:I0]Blizzard",
"[M:I0]Hyper Beam",
"[M:I0]Light Screen",
"[M:I0]Protect",
"$$$",
"[M:I0]Giga Drain",
"[M:I0]Safeguard",
"[M:I0]Frustration",
"[M:I0]SolarBeam",
"[M:I0]Iron Tail",
"[M:I0]Thunderbolt",
"[M:I0]Thunder",
"[M:I0]Earthquake",
"[M:I0]Return",
"[M:I0]Dig",
"[M:I0]Psychic",
"[M:I0]Shadow Ball",
"[M:I0]Brick Break",
"$$$",
"[M:I0]Reflect",
"[M:I0]Shock Wave",
"[M:I0]Flamethrower",
"[M:I0]Sludge Bomb",
"$$$",
"[M:I0]Fire Blast",
"$$$",
"[M:I0]Aerial Ace",
"[M:I0]Torment",
"[M:I0]Facade",
"[M:I0]Secret Power",
"[M:I0]Rest",
"[M:I0]Attract",
"[M:I0]Thief",
"[M:I0]Steel Wing",
"[M:I0]Skill Swap",
"$$$",
"[M:I0]Overheat",
"[M:I0]Roost",
"[M:I0]Focus Blast",
"[M:I0]Energy Ball",
"[M:I0]False Swipe",
"[M:I0]Brine",
"[M:I0]Fling",
"[M:I0]Charge Beam",
"[M:I0]Endure",
"[M:I0]Dragon Pulse",
"[M:I0]Drain Punch",
"[M:I0]Will-O-Wisp",
"[M:I0]Silver Wind",
"[M:I0]Embargo",
"[M:I0]Explosion",
"[M:I0]Shadow Claw",
"[M:I0]Payback",
"[M:I0]Recycle",
"[M:I0]Giga Impact",
"[M:I0]Rock Polish",
"[M:I0]Wide Slash",
"$$$",
"$$$",
"[M:I0]Vacuum-Cut",
"[M:I0]Dive",
"[M:I0]Flash",
"[M:I0]Stone Edge",
"[M:I0]Avalanche",
"[M:I0]Thunder Wave",
"[M:I0]Gyro Ball",
"[M:I0]Swords Dance",
"[M:I0]Stealth Rock",
"[M:I0]Psych Up",
"[M:I0]Captivate",
"[M:I0]Dark Pulse",
"[M:I0]Rock Slide",
"[M:I0]X-Scissor",
"[M:I0]Sleep Talk",
"[M:I0]Natural Gift",
"[M:I0]Poison Jab",
"[M:I0]Dream Eater",
"[M:I0]Grass Knot",
"[M:I0]Swagger",
"[M:I0]Pluck",
"[M:I0]U-turn",
"[M:I0]Substitute",
"[M:I0]Flash Cannon",
"[M:I0]Trick Room",
"[M:I0]Cut",
"[M:I0]Fly",
"[M:I0]Surf",
"[M:I0]Strength",
"[M:I0]Defog",
"[M:I0]Rock Smash",
"[M:I0]Waterfall",
"[M:I0]Rock Climb",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"$$$",
"[M:I1]Hail Orb",
"[M:I1]Sunny Orb",
"[M:I1]Rainy Orb",
"[M:I1]Evasion Orb",
"[M:I1]Sandy Orb",
"[M:I1]Rocky Orb",
"[M:I1]Snatch Orb",
"[M:I1]See-Trap Orb",
"[M:I1]Mug Orb",
"[M:I1]Rebound Orb",
"[M:I1]Lob Orb",
"[M:I1]Switcher Orb",
"[M:I1]Blowback Orb",
"[M:I1]Warp Orb",
"[M:I1]Transfer Orb",
"[M:I1]Slow Orb",
"[M:I1]Quick Orb",
"[M:I1]Luminous Orb",
"[M:I1]Petrify Orb",
"[M:I1]Stayaway Orb",
"[M:I1]Pounce Orb",
"[M:I1]Trawl Orb",
"[M:I1]Cleanse Orb",
"$$$",
"[M:I1]Decoy Orb",
"[M:I1]Slumber Orb",
"[M:I1]Totter Orb",
"[M:I1]Two-Edge Orb",
"[M:I1]Silence Orb",
"[M:I1]Escape Orb",
"[M:I1]Scanner Orb",
"[M:I1]Radar Orb",
"[M:I1]Drought Orb",
"[M:I1]Trapbust Orb",
"[M:I1]Rollcall Orb",
"[M:I1]Invisify Orb",
"[M:I1]One-Shot Orb",
"[M:I1]Identify Orb",
"$$$",
"[M:I1]Shocker Orb",
"[M:I1]Sizebust Orb",
"[M:I1]One-Room Orb",
"[M:I1]Fill-In Orb",
"[M:I1]Trapper Orb",
"$$$",
"[M:I1]Itemizer Orb",
"[M:I1]Hurl Orb",
"[M:I1]Mobile Orb",
"$$$",
"[M:I1]Stairs Orb",
"[M:I1]Longtoss Orb",
"[M:I1]Pierce Orb",
"$$$",
"[M:I1]Spurn Orb",
"[M:I1]Foe-Hold Orb",
"[M:I1]All-Mach Orb",
"[M:I1]Foe-Fear Orb",
"[M:I1]All-Hit Orb",
"[M:I1]Foe-Seal Orb",
"$$$",
"$$$",
"Link Box",
"$$$",
"Gorgeous Box",
"Gorgeous Box",
"Gorgeous Box",
"Heavy Box",
"Heavy Box",
"Heavy Box",
"Shiny Box",
"Shiny Box",
"Shiny Box",
"Nifty Box",
"Nifty Box",
"Nifty Box",
"Dainty Box",
"Dainty Box",
"Dainty Box",
"Glittery Box",
"Glittery Box",
"Glittery Box",
"Pretty Box",
"Pretty Box",
"Pretty Box",
"Deluxe Box",
"Deluxe Box",
"Deluxe Box",
"Light Box",
"Light Box",
"Light Box",
"Cute Box",
"Cute Box",
"Cute Box",
"Hard Box",
"Hard Box",
"Hard Box",
"Sinister Box",
"Sinister Box",
"Sinister Box",
"[FT:1]A[FT:0]-Stone",
"[FT:1]B[FT:0]-Stone",
"[FT:1]C[FT:0]-Stone",
"[FT:1]D[FT:0]-Stone",
"[FT:1]E[FT:0]-Stone",
"[FT:1]F[FT:0]-Stone",
"[FT:1]G[FT:0]-Stone",
"[FT:1]H[FT:0]-Stone",
"[FT:1]I[FT:0]-Stone",
"[FT:1]J[FT:0]-Stone",
"[FT:1]K[FT:0]-Stone",
"[FT:1]L[FT:0]-Stone",
"[FT:1]M[FT:0]-Stone",
"[FT:1]N[FT:0]-Stone",
"[FT:1]O[FT:0]-Stone",
"[FT:1]P[FT:0]-Stone",
"[FT:1]Q[FT:0]-Stone",
"[FT:1]R[FT:0]-Stone",
"[FT:1]S[FT:0]-Stone",
"[FT:1]T[FT:0]-Stone",
"[FT:1]U[FT:0]-Stone",
"[FT:1]V[FT:0]-Stone",
"[FT:1]W[FT:0]-Stone",
"[FT:1]X[FT:0]-Stone",
"[FT:1]Y[FT:0]-Stone",
"[FT:1]Z[FT:0]-Stone",
"[FT:1]![FT:0]-Stone",
"[FT:1]?[FT:0]-Stone",
"Silver Bow",
"Brown Bow",
"Red Bow",
"Pink Bow",
"Orange Bow",
"Yellow Bow",
"Lime Bow",
"Green Bow",
"Viridian Bow",
"Minty Bow",
"Sky Blue Bow",
"Blue Bow",
"Cobalt Bow",
"Purple Bow",
"Violet Bow",
"Fuchsia Bow",
"Prism Ruff",
"Aqua Collar",
"Volt Collar",
"Fire Collar",
"Light Collar",
"Dusk Collar",
"Virid Collar",
"Icy Collar",
"Pep Sash",
"Counter Ruff",
"Victory Belt",
"Power Bangle",
"Thundershard",
"Fallen Star",
"Fluff Dust",
"Egg Shard",
"Heroic Medal",
"Chic Shard",
"Yellow Jewel",
"Red Jewel",
"Blue Jewel",
"Laugh Dust",
"Guard Sand",
"Purple Jewel",
"White Jewel",
"Brave Dust",
"Heal Dew",
"Marine Cache",
"Freeze Veil",
"Thunder Veil",
"Fire Veil",
"Havoc Robe",
"Life Ring",
"Bolt Fang",
"Flare Fang",
"Aqua Mantle",
"Silver Veil",
"Rainbow Veil",
"Chrono Veil",
"Rock Sash",
"Ice Sash",
"Steel Sash",
"Heart Brooch",
"Eon Veil",
"Seabed Veil",
"Terra Ring",
"SkyHigh Veil",
"Wish Mantle",
"Revive Robe",
"Shadow Veil",
"Plasma Veil",
"Edify Robe",
"Charity Robe",
"Hope Robe",
"Time Shield",
"Air Blade",
"Searing Ring",
"Ancient Ring",
"Nether Veil",
"Lunar Veil",
"Tidal Cape",
"Eclipse Robe",
"White Silk",
"Normal Dust",
"White Gem",
"Joy Globe",
"Red Silk",
"Fire Dust",
"Fiery Gem",
"Fiery Globe",
"Blue Silk",
"Water Dust",
"Aqua Gem",
"Aqua Globe",
"Grass Silk",
"Grass Dust",
"Grass Gem",
"Soothe Globe",
"Yellow Silk",
"Thunder Dust",
"Thunder Gem",
"Volt Globe",
"Clear Silk",
"Icy Dust",
"Icy Gem",
"Icy Globe",
"Orange Silk",
"Courage Dust",
"Fight Gem",
"Power Globe",
"Pink Silk",
"Poison Dust",
"Poison Gem",
"Poison Globe",
"Brown Silk",
"Ground Dust",
"Earth Gem",
"Terra Globe",
"Sky Silk",
"Sky Dust",
"Sky Gem",
"Sky Globe",
"Gold Silk",
"Psyche Dust",
"Psyche Gem",
"Psyche Globe",
"Green Silk",
"Wonder Dust",
"Guard Gem",
"Defend Globe",
"Gray Silk",
"Rock Dust",
"Stone Gem",
"Rock Globe",
"Purple Silk",
"Shady Dust",
"Shadow Gem",
"Nether Globe",
"Royal Silk",
"Dragon Dust",
"Dragon Gem",
"Dragon Globe",
"Black Silk",
"Dark Dust",
"Dark Gem",
"Dusk Globe",
"Iron Silk",
"Steel Dust",
"Metal Gem",
"Steel Globe",
"Bulba-Claw",
"Bulba-Fang",
"Grass-Guard",
"Leafy Tie",
"Ivy-Claw",
"Ivy-Fang",
"Ivy-Crest",
"Plant Torc",
"Venus-Claw",
"Venus-Fang",
"Venus-Seal",
"Solar Sash",
"Char-Claw",
"Char-Fang",
"Fiery Heart",
"Heat Armlet",
"Charme-Claw",
"Charme-Fang",
"Charme-Crest",
"Kindle Scarf",
"Chariz-Claw",
"Chariz-Fang",
"Chariz-Seal",
"Flame Bangle",
"Squirt-Foam",
"Squirt-Card",
"Water-Guard",
"Aqua Tie",
"Wartor-Claw",
"Wartor-Fang",
"Wartor-Crest",
"BubbleBangle",
"Blasto-Claw",
"Blasto-Card",
"Blasto-Seal",
"Hydro Band",
"Pichu Hair",
"Pichu Card",
"Express Tag",
"Shocker Cape",
"Pikachu Hair",
"Pikachu Card",
"Volt Charm",
"Volt Torc",
"Raichu Hair",
"Raichu Card",
"Raichu Crest",
"Zapper Scarf",
"Meowth Claw",
"Meowth Fang",
"Coin Charm",
"Bling Ruff",
"Persian Claw",
"Persian Fang",
"Insight Rock",
"Noble Scarf",
"Chiko-Claw",
"Chiko-Card",
"Dawn Jewel",
"Fresh Bow",
"Bayleef Claw",
"Bayleef Card",
"Bayleef Seal",
"Spice Bow",
"Megani-Claw",
"Megani-Card",
"Shiny Charm",
"Bright Veil",
"Cynda-Hair",
"Cynda-Claw",
"Blazing Rock",
"Storm Sash",
"Quila-Hair",
"Quila-Card",
"Quila-Crest",
"Volcano Torc",
"Typhlo-Gasp",
"Typhlo-Fang",
"Typhlo-Seal",
"Blast Bangle",
"Totodi-Dew",
"Totodi-Fang",
"Water Heart",
"Wash Bow",
"Croco-Fang",
"Croco-Card",
"Swirl Rock",
"Anger Scarf",
"Feral-Claw",
"Feral-Fang",
"Feral-Crest",
"Hydro Jaw",
"Treeck-Thorn",
"Treeck-Card",
"Forest Ore",
"Guard Ring",
"Grovy-Shoot",
"Grovy-Card",
"Jungle-Tag",
"Grass Blade",
"Scept-Claw",
"Scept-Card",
"Scept-Seal",
"Drain Bangle",
"Torchic Hair",
"Torchic Card",
"Hot Pebble",
"Fire Cape",
"Combus-Sweat",
"Combus-Claw",
"Charge Tag",
"Gutsy Band",
"Blazi-Claw",
"Blazi-Card",
"Blazi-Seal",
"Blaze Torc",
"Mudkip Mud",
"Mudkip Card",
"Mud Jewel",
"Speed Scarf",
"Marsh-Mud",
"Marsh-Card",
"Marsh-Crest",
"Marsh Torc",
"Swamp-Mud",
"Swamp-Card",
"Swamp-Seal",
"Swamp Bangle",
"Skitty Fang",
"Skitty Card",
"Smile Pebble",
"Heal Pendant",
"Delcat-Hair",
"Delcat-Fang",
"Prim Pebble",
"Guard Collar",
"Lucky Leaf",
"Turtwig Card",
"Sprout Rock",
"Leafy Hat",
"Grotle Twig",
"Grotle Claw",
"Grotle Crest",
"Woody Scarf",
"Tort-Claw",
"Tort-Horn",
"Tort-Seal",
"Forest Torc",
"Chim-Hair",
"Chim-Fang",
"Nimble Charm",
"Ember Cap",
"Monfer-Hair",
"Monfer-Fang",
"Monfer-Crest",
"Burst Sash",
"Infern-Hair",
"Infern-Fang",
"Infern-Seal",
"Blazing Ruff",
"Piplup Foam",
"Piplup Card",
"Sea Ore",
"Water Cape",
"Prin-Foam",
"Prin-Card",
"Prin-Crest",
"Aqua Blade",
"Empol-Claw",
"Empol-Horn",
"Empol-Seal",
"Marine Crown",
"Munch-Drool",
"Munch-Claw",
"Tummy Charm",
"Glutton Cape",
"Snorlax Gasp",
"Snorlax Fang",
"Valor Charm",
"Glee Scarf",
"Scyther Fang",
"Scyther Card",
"Ambush Rock",
"Strike Ruff",
"Scizor Wing",
"Scizor Card",
"Steel Charm",
"Red Armlet",
"Lapras Song",
"Lapras Card",
"Wavy Charm",
"Mystic Scarf",
"Eevee Tail",
"Eevee Card",
"Evolve Charm",
"$$$",
"Cleffa Dew",
"Cleffa Card",
"Starry Ore",
"Comet Ring",
"Clef-Claw",
"Clef-Fang",
"Moon Jewel",
"Moon Scarf",
"Clefa-Claw",
"Clefa-Card",
"Moon Rock",
"Fairy Bow",
"Iggly-Dew",
"Iggly-Card",
"Bouncy Charm",
"Pretty Bow",
"Jiggly-Song",
"Jiggly-Card",
"Slumber Rock",
"Snooze Ring",
"Wiggly-Hair",
"Wiggly-Card",
"Buddy Rock",
"Friend Torc",
"Togepi Dew",
"Togepi Card",
"Pure Heart",
"Angel Scarf",
"Togetic Wing",
"Togetic Card",
"Happy Rock",
"Luck Brooch",
"Togek-Wing",
"Togek-Card",
"Ovation Rock",
"Glitter Robe",
"Sneasel Claw",
"Sneasel Card",
"Dusk Jewel",
"Cruel Ring",
"Weavile Claw",
"Weavile Fang",
"Vile Tag",
"Ruin Armlet",
"Teddi-Claw",
"Teddi-Card",
"Honey Rock",
"Heal Scarf",
"Ursa-Claw",
"Ursa-Fang",
"Calming Rock",
"Hiber Scarf",
"Tyro-Sweat",
"Tyro-Card",
"Muscle Charm",
"$$$",
"Smooch-Song",
"Smooch-Card",
"Kiss Charm",
"Heart Tiara",
"Jynx Song",
"Jynx Card",
"Frozen Ore",
"Ruin Scarf",
"Elekid Claw",
"Elekid Card",
"Jolt Charm",
"Current Ring",
"Electa-Claw",
"Electa-Fang",
"Charge Seal",
"Volt Bangle",
"Electi-Claw",
"Electi-Card",
"Voltaic Rock",
"Voltaic Band",
"Magby Claw",
"Magby Card",
"Ember Jewel",
"Coal Ring",
"Magmar Claw",
"Magmar Card",
"Erupt Ore",
"Magma Scarf",
"Magmor-Claw",
"Magmor-Card",
"Vulcan Rock",
"Burning Torc",
"Azuri-Dew",
"Azuri-Card",
"Fount Charm",
"Water Float",
"Marill Dew",
"Marill Card",
"Surfer Rock",
"Brine Scarf",
"Azuma-Dew",
"Azuma-Card",
"Stream Charm",
"Dotted Scarf",
"Plusle Tail",
"Plusle Card",
"Cheer Rock",
"Pulse Bow",
"Minun Tail",
"Minun Card",
"Volt Heart",
"Spark Tie",
"Cast-Dew",
"Cast-Card",
"Cloud Rock",
"Weather Cape",
"Wynaut Tail",
"Wynaut Card",
"Grin Charm",
"Cheery Scarf",
"Wobbu-Sweat",
"Wobbu-Card",
"Endure Rock",
"Suffer Scarf",
"Bidoof Tooth",
"Bidoof Card",
"Fall Charm",
"Stolid Scarf",
"Biba-Tooth",
"Biba-Card",
"River Charm",
"Dam Scarf",
"Shinx Claw",
"Shinx Fang",
"Flash Tag",
"Energy Scarf",
"Luxio Claw",
"Luxio Fang",
"Spark Tag",
"Spark Scarf",
"Luxray Claw",
"Luxray Fang",
"Glare Tag",
"Glare Sash",
"Pachi-Tooth",
"Pachi-Card",
"Rouse Charm",
"Miracle Bow",
"Buizel Fang",
"Buizel Card",
"Swimmer Rock",
"Screw Torc",
"Float-Fang",
"Float-Card",
"Rescue Rock",
"Float Aid",
"Drifloo-Gasp",
"Drifloo-Card",
"Wind Heart",
"Draft Ring",
"Drifbli-Gasp",
"Drifbli-Card",
"Easy Charm",
"Breeze Scarf",
"Cherubi Seed",
"Cherubi Card",
"Cute Ore",
"Charm Bow",
"Cherrim Dew",
"Cherrim Card",
"Sweet Aroma",
"Petal Dress",
"Bonsly Dew",
"Bonsly Card",
"Arid Tag",
"Teary Cape",
"Sudo-Sweat",
"Sudo-Card",
"Drain Rock",
"Fake Torc",
"Junior Beam",
"Junior Card",
"Mimic Pebble",
"Copy Mask",
"Mime Key",
"Mime Card",
"Bulwark Rock",
"Barrier Bow",
"Happiny Dew",
"Happiny Card",
"Play Tag",
"Nurture Cape",
"Chansey Song",
"Chansey Card",
"Lucky Charm",
"Lucky Scarf",
"Blissey Song",
"Blissey Card",
"Amity Rock",
"Faith Ring",
"Gible Fang",
"Gible Card",
"Dragon Jewel",
"Dragon Tie",
"Gabite Claw",
"Gabite Fang",
"Star Rock",
"Meteor Torc",
"Gar-Claw",
"Gar-Fang",
"Speed Tag",
"Mach Scarf",
"Riolu Tail",
"Riolu Card",
"Valiant Rock",
"Emit Ring",
"Lucario Fang",
"Lucario Card",
"Pledge Rock",
"Ravage Ring",
"Mantyke Beam",
"Mantyke Card",
"Waft Rock",
"Ocean Bow",
"Mantine Foam",
"Mantine Card",
"Sunset Rock",
"Horizon Bow",
"Phione Song",
"Phione Card",
"Wave Jewel",
"Ripple Cape",
"-",
"-"
]
